// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9d9b1dc4-ad19-4044-96ef-b1eb80ca31f9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_laYBiZPRL",
    "aws_user_pools_web_client_id": "6vdkn8qg8sls32kob9ggrstdlu",
    "oauth": {}
};


export default awsmobile;
